In [1]:
import tensorflow as tf
import numpy as np
print (tf.__version__)
print (np.__version__)

1.2.0
1.13.0


In [10]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]
 [  69.   74.   77.]
 [  47.   56.   60.]
 [  87.   79.   90.]
 [  79.   70.   88.]
 [  69.   70.   73.]
 [  70.   65.   74.]
 [  93.   95.   91.]
 [  79.   80.   73.]
 [  70.   73.   78.]
 [  93.   89.   96.]
 [  78.   75.   68.]
 [  81.   90.   93.]
 [  88.   92.   86.]
 [  78.   83.   77.]
 [  82.   86.   90.]
 [  86.   82.   89.]
 [  78.   83.   85.]
 [  76.   83.   71.]
 [  96.   93.   95.]] 25
(25, 1) [[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]
 [ 149.]
 [ 115.]
 [ 175.]
 [ 164.]
 [ 141.]
 [ 141.]
 [ 184.]
 [ 152.]
 [ 148.]
 [ 192.]
 [ 147.]
 [ 183.]
 [ 177.]
 [ 159.]
 [ 177.]
 [ 175.]
 [ 175.]
 [ 149.]
 [ 192.]]


In [20]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

In [21]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [22]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [25]:
for step in range(200001):
    cost_val, hy_val, _ = \
        sess.run([cost, hypothesis, train],
                feed_dict={X: x_data, Y: y_data})
    if step % 1000 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

0 Cost: 6.24417 
Prediction:
 [[ 153.05995178]
 [ 184.44520569]
 [ 181.31254578]
 [ 198.72071838]
 [ 139.91322327]
 [ 105.46997833]
 [ 150.73292542]
 [ 114.42816925]
 [ 174.19297791]
 [ 164.38691711]
 [ 144.07884216]
 [ 142.86332703]
 [ 185.94729614]
 [ 152.84831238]
 [ 151.66369629]
 [ 188.36264038]
 [ 144.19032288]
 [ 181.43382263]
 [ 177.00093079]
 [ 158.62545776]
 [ 176.24705505]
 [ 174.33534241]
 [ 167.6410675 ]
 [ 151.1829834 ]
 [ 190.40309143]]
1000 Cost: 6.242 
Prediction:
 [[ 153.04766846]
 [ 184.45983887]
 [ 181.31234741]
 [ 198.71650696]
 [ 139.93452454]
 [ 105.48214722]
 [ 150.71496582]
 [ 114.39347839]
 [ 174.20812988]
 [ 164.39422607]
 [ 144.07437134]
 [ 142.87008667]
 [ 185.95193481]
 [ 152.85977173]
 [ 151.64952087]
 [ 188.37084961]
 [ 144.21520996]
 [ 181.40332031]
 [ 177.00146484]
 [ 158.62182617]
 [ 176.23197937]
 [ 174.34300232]
 [ 167.62533569]
 [ 151.18154907]
 [ 190.41575623]]
2000 Cost: 6.24052 
Prediction:
 [[ 153.03811646]
 [ 184.47123718]
 [ 181.31222534]
 [ 

18000 Cost: 6.2327 
Prediction:
 [[ 153.00320435]
 [ 184.5133667 ]
 [ 181.31410217]
 [ 198.70736694]
 [ 140.00390625]
 [ 105.51456451]
 [ 150.6506958 ]
 [ 114.26569366]
 [ 174.26208496]
 [ 164.41964722]
 [ 144.05554199]
 [ 142.88987732]
 [ 185.97113037]
 [ 152.89706421]
 [ 151.59854126]
 [ 188.40301514]
 [ 144.29733276]
 [ 181.30075073]
 [ 177.00502014]
 [ 158.60806274]
 [ 176.18177795]
 [ 174.3710022 ]
 [ 167.57144165]
 [ 151.17399597]
 [ 190.46340942]]
19000 Cost: 6.23232 
Prediction:
 [[ 153.00299072]
 [ 184.51373291]
 [ 181.31430054]
 [ 198.70774841]
 [ 140.00378418]
 [ 105.5139389 ]
 [ 150.65039062]
 [ 114.26480103]
 [ 174.2623291 ]
 [ 164.41969299]
 [ 144.05525208]
 [ 142.88967896]
 [ 185.97143555]
 [ 152.89703369]
 [ 151.5982666 ]
 [ 188.40335083]
 [ 144.29730225]
 [ 181.3006897 ]
 [ 177.00518799]
 [ 158.60798645]
 [ 176.18179321]
 [ 174.3711853 ]
 [ 167.5713501 ]
 [ 151.17382812]
 [ 190.46383667]]
20000 Cost: 6.23193 
Prediction:
 [[ 153.00279236]
 [ 184.51405334]
 [ 181.314498

36000 Cost: 6.22581 
Prediction:
 [[ 153.00006104]
 [ 184.51815796]
 [ 181.31756592]
 [ 198.71429443]
 [ 139.99949646]
 [ 105.50216675]
 [ 150.64659119]
 [ 114.25289154]
 [ 174.26455688]
 [ 164.41946411]
 [ 144.05070496]
 [ 142.88523865]
 [ 185.97590637]
 [ 152.8951416 ]
 [ 151.59477234]
 [ 188.40826416]
 [ 144.29425049]
 [ 181.30256653]
 [ 177.00769043]
 [ 158.6065979 ]
 [ 176.18327332]
 [ 174.37319946]
 [ 167.5710907 ]
 [ 151.17114258]
 [ 190.46942139]]
37000 Cost: 6.22544 
Prediction:
 [[ 152.99992371]
 [ 184.51838684]
 [ 181.31774902]
 [ 198.71470642]
 [ 139.99920654]
 [ 105.50147247]
 [ 150.6464386 ]
 [ 114.25229645]
 [ 174.26469421]
 [ 164.41949463]
 [ 144.05046082]
 [ 142.88499451]
 [ 185.97615051]
 [ 152.89497375]
 [ 151.59461975]
 [ 188.40853882]
 [ 144.29397583]
 [ 181.30278015]
 [ 177.00782776]
 [ 158.60650635]
 [ 176.18341064]
 [ 174.37332153]
 [ 167.57112122]
 [ 151.17095947]
 [ 190.46974182]]
38000 Cost: 6.22506 
Prediction:
 [[ 152.99975586]
 [ 184.51861572]
 [ 181.31793

54000 Cost: 6.21914 
Prediction:
 [[ 152.99728394]
 [ 184.52212524]
 [ 181.32077026]
 [ 198.72132874]
 [ 139.99404907]
 [ 105.48984528]
 [ 150.64378357]
 [ 114.24271393]
 [ 174.26669312]
 [ 164.41998291]
 [ 144.0463562 ]
 [ 142.8808136 ]
 [ 185.9798584 ]
 [ 152.89196777]
 [ 151.59222412]
 [ 188.41322327]
 [ 144.28909302]
 [ 181.30633545]
 [ 177.00973511]
 [ 158.60482788]
 [ 176.18582153]
 [ 174.37524414]
 [ 167.57174683]
 [ 151.16751099]
 [ 190.47454834]]
55000 Cost: 6.21878 
Prediction:
 [[ 152.99714661]
 [ 184.52235413]
 [ 181.32093811]
 [ 198.72172546]
 [ 139.99372864]
 [ 105.48916626]
 [ 150.64364624]
 [ 114.24217987]
 [ 174.26679993]
 [ 164.42002869]
 [ 144.04611206]
 [ 142.88056946]
 [ 185.98008728]
 [ 152.89176941]
 [ 151.59208679]
 [ 188.41349792]
 [ 144.28878784]
 [ 181.30654907]
 [ 177.00984192]
 [ 158.60473633]
 [ 176.18597412]
 [ 174.37535095]
 [ 167.5717926 ]
 [ 151.16731262]
 [ 190.47480774]]
56000 Cost: 6.2184 
Prediction:
 [[ 152.99697876]
 [ 184.52255249]
 [ 181.321105

72000 Cost: 6.21254 
Prediction:
 [[ 152.99459839]
 [ 184.52597046]
 [ 181.32392883]
 [ 198.72836304]
 [ 139.98843384]
 [ 105.47750854]
 [ 150.64115906]
 [ 114.23292542]
 [ 174.26870728]
 [ 164.42048645]
 [ 144.04206848]
 [ 142.87637329]
 [ 185.98373413]
 [ 152.88864136]
 [ 151.58981323]
 [ 188.41812134]
 [ 144.28370667]
 [ 181.31034851]
 [ 177.01171875]
 [ 158.60307312]
 [ 176.18850708]
 [ 174.37722778]
 [ 167.57254028]
 [ 151.16384888]
 [ 190.47949219]]
73000 Cost: 6.21219 
Prediction:
 [[ 152.99446106]
 [ 184.52618408]
 [ 181.32411194]
 [ 198.72875977]
 [ 139.9881134 ]
 [ 105.47682953]
 [ 150.64100647]
 [ 114.23238373]
 [ 174.26882935]
 [ 164.42051697]
 [ 144.04182434]
 [ 142.87611389]
 [ 185.98396301]
 [ 152.88845825]
 [ 151.58969116]
 [ 188.41838074]
 [ 144.28340149]
 [ 181.31056213]
 [ 177.01182556]
 [ 158.60298157]
 [ 176.18865967]
 [ 174.37733459]
 [ 167.57258606]
 [ 151.16363525]
 [ 190.47976685]]
74000 Cost: 6.21182 
Prediction:
 [[ 152.99430847]
 [ 184.52639771]
 [ 181.32427

90000 Cost: 6.20601 
Prediction:
 [[ 152.9919281 ]
 [ 184.52981567]
 [ 181.3270874 ]
 [ 198.73539734]
 [ 139.98278809]
 [ 105.46516418]
 [ 150.63853455]
 [ 114.2231369 ]
 [ 174.27072144]
 [ 164.42098999]
 [ 144.03778076]
 [ 142.87191772]
 [ 185.98760986]
 [ 152.8853302 ]
 [ 151.5874176 ]
 [ 188.42300415]
 [ 144.27832031]
 [ 181.31436157]
 [ 177.01370239]
 [ 158.60131836]
 [ 176.19119263]
 [ 174.37921143]
 [ 167.57333374]
 [ 151.16018677]
 [ 190.48443604]]
91000 Cost: 6.20564 
Prediction:
 [[ 152.99177551]
 [ 184.53001404]
 [ 181.32728577]
 [ 198.73579407]
 [ 139.98248291]
 [ 105.46447754]
 [ 150.63839722]
 [ 114.22260284]
 [ 174.27082825]
 [ 164.42102051]
 [ 144.03755188]
 [ 142.87167358]
 [ 185.98783875]
 [ 152.88514709]
 [ 151.58729553]
 [ 188.42327881]
 [ 144.27801514]
 [ 181.31459045]
 [ 177.0138092 ]
 [ 158.60124207]
 [ 176.19134521]
 [ 174.37931824]
 [ 167.57339478]
 [ 151.15997314]
 [ 190.48472595]]
92000 Cost: 6.20528 
Prediction:
 [[ 152.99163818]
 [ 184.53024292]
 [ 181.32745

108000 Cost: 6.19949 
Prediction:
 [[ 152.98924255]
 [ 184.53364563]
 [ 181.33026123]
 [ 198.74243164]
 [ 139.97717285]
 [ 105.45282745]
 [ 150.63592529]
 [ 114.21337128]
 [ 174.2727356 ]
 [ 164.42150879]
 [ 144.0335083 ]
 [ 142.86747742]
 [ 185.9914856 ]
 [ 152.88200378]
 [ 151.58502197]
 [ 188.42790222]
 [ 144.27290344]
 [ 181.31840515]
 [ 177.01568604]
 [ 158.59957886]
 [ 176.19387817]
 [ 174.38119507]
 [ 167.57415771]
 [ 151.15649414]
 [ 190.4894104 ]]
109000 Cost: 6.19914 
Prediction:
 [[ 152.98908997]
 [ 184.53385925]
 [ 181.33044434]
 [ 198.74284363]
 [ 139.97685242]
 [ 105.45214081]
 [ 150.63577271]
 [ 114.21282196]
 [ 174.27284241]
 [ 164.42152405]
 [ 144.03326416]
 [ 142.86723328]
 [ 185.99171448]
 [ 152.88182068]
 [ 151.5848999 ]
 [ 188.42817688]
 [ 144.27261353]
 [ 181.31863403]
 [ 177.01580811]
 [ 158.59947205]
 [ 176.19403076]
 [ 174.38130188]
 [ 167.57420349]
 [ 151.15629578]
 [ 190.48968506]]
110000 Cost: 6.19878 
Prediction:
 [[ 152.98895264]
 [ 184.53407288]
 [ 181.33

126000 Cost: 6.1931 
Prediction:
 [[ 152.98658752]
 [ 184.53744507]
 [ 181.33340454]
 [ 198.74938965]
 [ 139.97158813]
 [ 105.44061279]
 [ 150.6333313 ]
 [ 114.20368195]
 [ 174.27471924]
 [ 164.42199707]
 [ 144.02926636]
 [ 142.86306763]
 [ 185.99533081]
 [ 152.87872314]
 [ 151.5826416 ]
 [ 188.43273926]
 [ 144.26757812]
 [ 181.3223877 ]
 [ 177.01766968]
 [ 158.59783936]
 [ 176.1965332 ]
 [ 174.38314819]
 [ 167.57495117]
 [ 151.15286255]
 [ 190.49432373]]
127000 Cost: 6.19277 
Prediction:
 [[ 152.98643494]
 [ 184.53764343]
 [ 181.33357239]
 [ 198.74977112]
 [ 139.97129822]
 [ 105.43995667]
 [ 150.63319397]
 [ 114.20315552]
 [ 174.27484131]
 [ 164.42204285]
 [ 144.02903748]
 [ 142.86283875]
 [ 185.99552917]
 [ 152.87852478]
 [ 151.58251953]
 [ 188.43299866]
 [ 144.26725769]
 [ 181.32261658]
 [ 177.01776123]
 [ 158.59773254]
 [ 176.19668579]
 [ 174.383255  ]
 [ 167.57498169]
 [ 151.15266418]
 [ 190.49458313]]
128000 Cost: 6.1924 
Prediction:
 [[ 152.98629761]
 [ 184.53787231]
 [ 181.3337

144000 Cost: 6.18687 
Prediction:
 [[ 152.98399353]
 [ 184.54118347]
 [ 181.33647156]
 [ 198.75624084]
 [ 139.96614075]
 [ 105.42863464]
 [ 150.63078308]
 [ 114.19419098]
 [ 174.27668762]
 [ 164.42250061]
 [ 144.02510071]
 [ 142.85874939]
 [ 185.99908447]
 [ 152.87550354]
 [ 151.58032227]
 [ 188.43748474]
 [ 144.2623291 ]
 [ 181.3263092 ]
 [ 177.01957703]
 [ 158.59614563]
 [ 176.19914246]
 [ 174.38508606]
 [ 167.57572937]
 [ 151.14930725]
 [ 190.49913025]]
145000 Cost: 6.18653 
Prediction:
 [[ 152.98384094]
 [ 184.54138184]
 [ 181.3366394 ]
 [ 198.75660706]
 [ 139.96583557]
 [ 105.42796326]
 [ 150.63064575]
 [ 114.19366455]
 [ 174.27679443]
 [ 164.42251587]
 [ 144.02487183]
 [ 142.85852051]
 [ 185.9992981 ]
 [ 152.87530518]
 [ 151.5802002 ]
 [ 188.43774414]
 [ 144.26202393]
 [ 181.32653809]
 [ 177.01968384]
 [ 158.59603882]
 [ 176.19927979]
 [ 174.38519287]
 [ 167.57577515]
 [ 151.14910889]
 [ 190.49938965]]
146000 Cost: 6.18619 
Prediction:
 [[ 152.98370361]
 [ 184.54159546]
 [ 181.33

162000 Cost: 6.18071 
Prediction:
 [[ 152.98138428]
 [ 184.54489136]
 [ 181.33953857]
 [ 198.76306152]
 [ 139.96069336]
 [ 105.41667175]
 [ 150.62823486]
 [ 114.18470001]
 [ 174.27862549]
 [ 164.42298889]
 [ 144.02095032]
 [ 142.85444641]
 [ 186.00283813]
 [ 152.87228394]
 [ 151.57800293]
 [ 188.44223022]
 [ 144.25709534]
 [ 181.3302002 ]
 [ 177.02151489]
 [ 158.59443665]
 [ 176.20175171]
 [ 174.38699341]
 [ 167.57649231]
 [ 151.14575195]
 [ 190.50393677]]
163000 Cost: 6.18036 
Prediction:
 [[ 152.98124695]
 [ 184.54508972]
 [ 181.33970642]
 [ 198.76341248]
 [ 139.96038818]
 [ 105.416008  ]
 [ 150.62809753]
 [ 114.18418121]
 [ 174.2787323 ]
 [ 164.42301941]
 [ 144.02072144]
 [ 142.85420227]
 [ 186.0030365 ]
 [ 152.87210083]
 [ 151.5778656 ]
 [ 188.44248962]
 [ 144.25680542]
 [ 181.33042908]
 [ 177.0216217 ]
 [ 158.59434509]
 [ 176.20188904]
 [ 174.38710022]
 [ 167.57653809]
 [ 151.14555359]
 [ 190.50419617]]
164000 Cost: 6.18003 
Prediction:
 [[ 152.9810791 ]
 [ 184.54528809]
 [ 181.33

180000 Cost: 6.17458 
Prediction:
 [[ 152.97879028]
 [ 184.5486145 ]
 [ 181.34262085]
 [ 198.76986694]
 [ 139.95523071]
 [ 105.40472412]
 [ 150.6257019 ]
 [ 114.17523956]
 [ 174.28057861]
 [ 164.42349243]
 [ 144.01679993]
 [ 142.85014343]
 [ 186.00656128]
 [ 152.86904907]
 [ 151.57568359]
 [ 188.44696045]
 [ 144.25186157]
 [ 181.3341217 ]
 [ 177.0234375 ]
 [ 158.59272766]
 [ 176.2043457 ]
 [ 174.38891602]
 [ 167.57727051]
 [ 151.1421814 ]
 [ 190.50872803]]
181000 Cost: 6.17424 
Prediction:
 [[ 152.97865295]
 [ 184.54881287]
 [ 181.3427887 ]
 [ 198.77023315]
 [ 139.9549408 ]
 [ 105.40406036]
 [ 150.62556458]
 [ 114.17471313]
 [ 174.28068542]
 [ 164.42350769]
 [ 144.01657104]
 [ 142.84989929]
 [ 186.00679016]
 [ 152.86888123]
 [ 151.57554626]
 [ 188.44723511]
 [ 144.25157166]
 [ 181.33433533]
 [ 177.02354431]
 [ 158.59263611]
 [ 176.20449829]
 [ 174.38902283]
 [ 167.57731628]
 [ 151.14198303]
 [ 190.50898743]]
182000 Cost: 6.17391 
Prediction:
 [[ 152.97850037]
 [ 184.54901123]
 [ 181.34

198000 Cost: 6.16858 
Prediction:
 [[ 152.97622681]
 [ 184.55227661]
 [ 181.34564209]
 [ 198.77658081]
 [ 139.94985962]
 [ 105.39292145]
 [ 150.62319946]
 [ 114.16589355]
 [ 174.28250122]
 [ 164.42398071]
 [ 144.01271057]
 [ 142.84590149]
 [ 186.01028442]
 [ 152.86587524]
 [ 151.57339478]
 [ 188.45162964]
 [ 144.2467041 ]
 [ 181.33798218]
 [ 177.02532959]
 [ 158.59106445]
 [ 176.20692444]
 [ 174.39080811]
 [ 167.57803345]
 [ 151.13867188]
 [ 190.51345825]]
199000 Cost: 6.16825 
Prediction:
 [[ 152.97608948]
 [ 184.55247498]
 [ 181.34580994]
 [ 198.77696228]
 [ 139.9495697 ]
 [ 105.39226532]
 [ 150.62306213]
 [ 114.16537476]
 [ 174.28260803]
 [ 164.42399597]
 [ 144.01249695]
 [ 142.84567261]
 [ 186.01048279]
 [ 152.8657074 ]
 [ 151.57325745]
 [ 188.4519043 ]
 [ 144.24641418]
 [ 181.33818054]
 [ 177.0254364 ]
 [ 158.59095764]
 [ 176.20706177]
 [ 174.39091492]
 [ 167.57807922]
 [ 151.13850403]
 [ 190.51374817]]
200000 Cost: 6.16792 
Prediction:
 [[ 152.97593689]
 [ 184.55265808]
 [ 181.34

In [26]:
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[ 186.50569153]]
Other scores will be  [[ 182.37368774]
 [ 175.2313385 ]]


In [27]:
filename_queue = tf.train.string_input_producer(['data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

In [29]:
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b    

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [34]:
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = \
        sess.run([cost, hypothesis, train],
                feed_dict={X: x_batch, Y: y_batch})
    if step % 1000 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)
        
coord.request_stop()
coord.join(threads)

0 Cost: 4.47422 
Prediction:
 [[ 151.54130554]
 [ 190.02174377]
 [ 153.2225647 ]
 [ 183.90101624]
 [ 181.19554138]
 [ 198.53096008]
 [ 139.29283142]
 [ 104.68576813]
 [ 150.5944519 ]
 [ 114.38600922]]
1000 Cost: 5.33606 
Prediction:
 [[ 151.90097046]
 [ 190.76545715]
 [ 153.65083313]
 [ 184.67289734]
 [ 181.82093811]
 [ 199.24642944]
 [ 139.91668701]
 [ 105.2279129 ]
 [ 151.10824585]
 [ 114.7290802 ]]
2000 Cost: 5.2564 
Prediction:
 [[ 151.76864624]
 [ 190.79772949]
 [ 153.55963135]
 [ 184.73944092]
 [ 181.79429626]
 [ 199.23718262]
 [ 139.99447632]
 [ 105.33554077]
 [ 151.0806427 ]
 [ 114.67469788]]


In [35]:
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[ 185.22618103]]
Other scores will be  [[ 182.35868835]
 [ 175.58041382]]
