In [1]:
import tensorflow as tf
tf.__version__

'1.2.0'

In [29]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

In [30]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b
print(hypothesis)

Tensor("add_8:0", dtype=float32)


In [31]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [32]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [34]:
for step in range(20001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  15.666 
Prediction:
 [ 146.09994507  188.39505005  179.0350647   194.48434448  147.36325073]
100 Cost:  14.8501 
Prediction:
 [ 146.25048828  188.29174805  179.08106995  194.51870728  147.22679138]
200 Cost:  14.0772 
Prediction:
 [ 146.39698792  188.19120789  179.12580872  194.55213928  147.09393311]
300 Cost:  13.3452 
Prediction:
 [ 146.53953552  188.09333801  179.16932678  194.5847168   146.96461487]
400 Cost:  12.6516 
Prediction:
 [ 146.67829895  187.99810791  179.2117157   194.61643982  146.83874512]
500 Cost:  11.9948 
Prediction:
 [ 146.81330872  187.90544128  179.25294495  194.64733887  146.71621704]
600 Cost:  11.3725 
Prediction:
 [ 146.94474792  187.81526184  179.29307556  194.67744446  146.59698486]
700 Cost:  10.7831 
Prediction:
 [ 147.07261658  187.72747803  179.33210754  194.70674133  146.480896  ]
800 Cost:  10.2247 
Prediction:
 [ 147.19708252  187.64205933  179.37011719  194.73530579  146.36790466]
900 Cost:  9.69576 
Prediction:
 [ 147.31819153  187.55892

7800 Cost:  0.415183 
Prediction:
 [ 151.03208923  185.00619507  180.53631592  195.64639282  142.8522644 ]
7900 Cost:  0.403122 
Prediction:
 [ 151.04992676  184.99388123  180.54167175  195.65113831  142.83535767]
8000 Cost:  0.391683 
Prediction:
 [ 151.06730652  184.98190308  180.54689026  195.6558075   142.81890869]
8100 Cost:  0.380846 
Prediction:
 [ 151.08418274  184.9702301   180.55194092  195.6603241   142.8028717 ]
8200 Cost:  0.370571 
Prediction:
 [ 151.1006012   184.95889282  180.55685425  195.66473389  142.7872467 ]
8300 Cost:  0.360825 
Prediction:
 [ 151.11656189  184.94784546  180.56161499  195.66906738  142.77201843]
8400 Cost:  0.35159 
Prediction:
 [ 151.1321106   184.93711853  180.56626892  195.67330933  142.75721741]
8500 Cost:  0.342832 
Prediction:
 [ 151.14723206  184.92668152  180.57080078  195.67745972  142.74278259]
8600 Cost:  0.334534 
Prediction:
 [ 151.16192627  184.91651917  180.57519531  195.68147278  142.72871399]
8700 Cost:  0.326666 
Prediction:
 [ 1

15600 Cost:  0.182268 
Prediction:
 [ 151.60368347  184.608078    180.70323181  195.82946777  142.27758789]
15700 Cost:  0.181984 
Prediction:
 [ 151.60557556  184.60671997  180.70372009  195.83053589  142.27520752]
15800 Cost:  0.181706 
Prediction:
 [ 151.60736084  184.6053772   180.70414734  195.83158875  142.27285767]
15900 Cost:  0.18144 
Prediction:
 [ 151.60914612  184.60411072  180.7046051   195.83262634  142.27059937]
16000 Cost:  0.181188 
Prediction:
 [ 151.61083984  184.6028595   180.70504761  195.83364868  142.26834106]
16100 Cost:  0.180933 
Prediction:
 [ 151.61248779  184.60166931  180.70544434  195.83467102  142.26617432]
16200 Cost:  0.180694 
Prediction:
 [ 151.61410522  184.60049438  180.70585632  195.8356781   142.26403809]
16300 Cost:  0.180462 
Prediction:
 [ 151.61564636  184.59936523  180.70623779  195.83666992  142.26196289]
16400 Cost:  0.18023 
Prediction:
 [ 151.61715698  184.59828186  180.706604    195.83764648  142.25991821]
16500 Cost:  0.180012 
Predict

In [35]:
print(sess.run(hypothesis, feed_dict={x1: 10, x2: 76, x3: 88}))

[ 84.74430084]


In [36]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b


In [37]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [39]:
for step in range(20001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  2.38128 
Prediction:
 [[ 149.31364441]
 [ 185.88749695]
 [ 179.73320007]
 [ 197.88233948]
 [ 141.46347046]]
100 Cost:  2.34637 
Prediction:
 [[ 149.34379578]
 [ 185.86741638]
 [ 179.74320984]
 [ 197.88337708]
 [ 141.44236755]]
200 Cost:  2.31292 
Prediction:
 [[ 149.37322998]
 [ 185.84788513]
 [ 179.7530365 ]
 [ 197.88430786]
 [ 141.42193604]]
300 Cost:  2.28085 
Prediction:
 [[ 149.40193176]
 [ 185.8288269 ]
 [ 179.76261902]
 [ 197.88508606]
 [ 141.40213013]]
400 Cost:  2.25008 
Prediction:
 [[ 149.42996216]
 [ 185.81027222]
 [ 179.77200317]
 [ 197.88574219]
 [ 141.38293457]]
500 Cost:  2.22057 
Prediction:
 [[ 149.45727539]
 [ 185.79214478]
 [ 179.78115845]
 [ 197.88624573]
 [ 141.36433411]]
600 Cost:  2.1922 
Prediction:
 [[ 149.4839325 ]
 [ 185.7744751 ]
 [ 179.79011536]
 [ 197.88659668]
 [ 141.34631348]]
700 Cost:  2.16495 
Prediction:
 [[ 149.50996399]
 [ 185.75724792]
 [ 179.7988739 ]
 [ 197.88684082]
 [ 141.32885742]]
800 Cost:  2.13876 
Prediction:
 [[ 149.53535461]
 

6900 Cost:  1.40559 
Prediction:
 [[ 150.35870361]
 [ 185.21087646]
 [ 180.10397339]
 [ 197.75683594]
 [ 140.9080658 ]]
7000 Cost:  1.39909 
Prediction:
 [[ 150.36532593]
 [ 185.20687866]
 [ 180.10668945]
 [ 197.75357056]
 [ 140.90724182]]
7100 Cost:  1.39266 
Prediction:
 [[ 150.37181091]
 [ 185.20294189]
 [ 180.10934448]
 [ 197.7502594 ]
 [ 140.90649414]]
7200 Cost:  1.38628 
Prediction:
 [[ 150.37820435]
 [ 185.1991272 ]
 [ 180.11198425]
 [ 197.7469635 ]
 [ 140.90586853]]
7300 Cost:  1.37998 
Prediction:
 [[ 150.38446045]
 [ 185.19534302]
 [ 180.11456299]
 [ 197.74363708]
 [ 140.90530396]]
7400 Cost:  1.37371 
Prediction:
 [[ 150.39059448]
 [ 185.19161987]
 [ 180.11709595]
 [ 197.74026489]
 [ 140.90481567]]
7500 Cost:  1.36751 
Prediction:
 [[ 150.39665222]
 [ 185.1880188 ]
 [ 180.11962891]
 [ 197.73692322]
 [ 140.9044342 ]]
7600 Cost:  1.36136 
Prediction:
 [[ 150.40261841]
 [ 185.18447876]
 [ 180.12213135]
 [ 197.73358154]
 [ 140.90414429]]
7700 Cost:  1.35525 
Prediction:
 [[ 150

14000 Cost:  1.04089 
Prediction:
 [[ 150.65007019]
 [ 185.04574585]
 [ 180.23716736]
 [ 197.51124573]
 [ 140.98023987]]
14100 Cost:  1.03671 
Prediction:
 [[ 150.65270996]
 [ 185.04437256]
 [ 180.23854065]
 [ 197.50782776]
 [ 140.98217773]]
14200 Cost:  1.03257 
Prediction:
 [[ 150.65531921]
 [ 185.04302979]
 [ 180.23989868]
 [ 197.50440979]
 [ 140.9841156 ]]
14300 Cost:  1.02844 
Prediction:
 [[ 150.65791321]
 [ 185.04170227]
 [ 180.24125671]
 [ 197.50100708]
 [ 140.98608398]]
14400 Cost:  1.02434 
Prediction:
 [[ 150.66047668]
 [ 185.04039001]
 [ 180.24261475]
 [ 197.49760437]
 [ 140.98803711]]
14500 Cost:  1.02025 
Prediction:
 [[ 150.66305542]
 [ 185.0390625 ]
 [ 180.24395752]
 [ 197.49423218]
 [ 140.99002075]]
14600 Cost:  1.0162 
Prediction:
 [[ 150.66557312]
 [ 185.03778076]
 [ 180.24528503]
 [ 197.49082947]
 [ 140.99197388]]
14700 Cost:  1.01215 
Prediction:
 [[ 150.66807556]
 [ 185.03648376]
 [ 180.24659729]
 [ 197.48744202]
 [ 140.99395752]]
14800 Cost:  1.00812 
Prediction: