In [2]:
import tensorflow as tf
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [6]:
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

x_test = [[2, 1, 1], [3, 1, 2], [3, 3, 4]]
y_test = [[0, 0, 1], [0, 0, 1], [0, 0, 1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

logits = tf.matmul(X, W) + b
hypothesis = tf.nn.softmax(logits)
cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits,
                                                labels=Y)

cost = tf.reduce_mean(cost_i)
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [8]:
sess = tf.Session()

sess.run(tf.global_variables_initializer())

feed = {X: x_data, Y: y_data}

for step in range(2001):
    cost_val, W_val, _ = sess.run([cost, W, optimizer], 
                                 feed_dict=feed)
    if step % 100 == 0:
        print(step, "\n", cost_val, "\n", W_val)

0 
 9.55048 
 [[ 0.36391199  1.4717505   0.35529885]
 [-0.62531924  0.91852117 -0.49155396]
 [-0.96634912  0.78120142 -0.03645778]]
100 
 0.783861 
 [[-0.68905973  1.2619046   1.61811662]
 [ 0.02073774 -0.163416   -0.05567373]
 [ 0.04317401  0.211301   -0.47608054]]
200 
 0.635626 
 [[-1.27396536  1.2628696   2.20205712]
 [ 0.07097928 -0.12878148 -0.14054957]
 [ 0.2263608   0.19965297 -0.64761919]]
300 
 0.564656 
 [[-1.69823575  1.30081797  2.58837986]
 [ 0.08724387 -0.10123163 -0.18436398]
 [ 0.37579632  0.17505635 -0.77245837]]
400 
 0.517423 
 [[-2.05241752  1.35235989  2.89102006]
 [ 0.09099172 -0.08360486 -0.20573851]
 [ 0.50829732  0.15126722 -0.88116997]]
500 
 0.481574 
 [[-2.36451149  1.40745091  3.14802313]
 [ 0.09059821 -0.07126763 -0.21768223]
 [ 0.62759984  0.12900296 -0.97820848]]
600 
 0.45261 
 [[-2.64665723  1.46179998  3.37581992]
 [ 0.0889613  -0.06201826 -0.22529468]
 [ 0.73612511  0.10852022 -1.06625104]]
700 
 0.428368 
 [[-2.90547252  1.51356626  3.58286858]
 [ 

In [9]:
print("Prediction: ", sess.run(prediction, feed_dict={X: x_test}))

print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

Prediction:  [2 2 2]
Accuracy:  1.0


In [6]:
tf.set_random_seed(777)
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
scaler = MinMaxScaler(feature_range=(0, 1))
xy = scaler.fit_transform(xy)

print(xy)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5).minimize(cost)

[[ 1.          1.          0.          1.          1.        ]
 [ 0.70548491  0.70439552  1.          0.71881783  0.83755792]
 [ 0.54412549  0.50274824  0.57608696  0.60646801  0.6606331 ]
 [ 0.33890353  0.31368023  0.10869565  0.45989134  0.43800918]
 [ 0.51436     0.4258239   0.30434783  0.58504805  0.42624401]
 [ 0.49556179  0.4258239   0.31521739  0.48131134  0.49276137]
 [ 0.11436064  0.          0.20652174  0.22007776  0.18597238]
 [ 0.          0.07747099  0.5326087   0.          0.        ]]


In [5]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

feed = {X: x_data, Y: y_data}

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, optimizer], feed_dict=feed)
    
    if step % 100 == 0 :
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  0.152309 
Prediction:
 [[ 1.63461912]
 [ 0.06613699]
 [ 0.35008186]
 [ 0.67072523]
 [ 0.6113075 ]
 [ 0.61464405]
 [ 0.23171967]
 [-0.13728359]]
100 Cost:  0.152254 
Prediction:
 [[ 1.63450289]
 [ 0.06628087]
 [ 0.35014752]
 [ 0.67070574]
 [ 0.61131608]
 [ 0.61466062]
 [ 0.23175186]
 [-0.13716528]]
200 Cost:  0.152199 
Prediction:
 [[ 1.63438666]
 [ 0.06642482]
 [ 0.35021317]
 [ 0.67068636]
 [ 0.61132473]
 [ 0.61467707]
 [ 0.231784  ]
 [-0.13704696]]
300 Cost:  0.152144 
Prediction:
 [[ 1.63427043]
 [ 0.06656882]
 [ 0.35027897]
 [ 0.67066693]
 [ 0.61133337]
 [ 0.61469364]
 [ 0.23181619]
 [-0.13692865]]
400 Cost:  0.152088 
Prediction:
 [[ 1.6341542 ]
 [ 0.06671271]
 [ 0.35034463]
 [ 0.6706475 ]
 [ 0.61134201]
 [ 0.61471015]
 [ 0.23184836]
 [-0.13681027]]
500 Cost:  0.152033 
Prediction:
 [[ 1.63403797]
 [ 0.06685665]
 [ 0.35041028]
 [ 0.67062807]
 [ 0.61135066]
 [ 0.61472666]
 [ 0.23188052]
 [-0.13669196]]
600 Cost:  0.151978 
Prediction:
 [[ 1.63392174]
 [ 0.0670006 ]
 [ 0.350