In [2]:
import tensorflow as tf
import numpy as np
import pprint

tf.set_random_seed(777)
pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [3]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim)
print(t.shape)
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.])
1
(7,)
0.0 1.0 6.0
[ 2.  3.  4.] [ 4.  5.]
[ 0.  1.] [ 3.  4.  5.  6.]


## 2D Array

In [4]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim)
print(t.shape)

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])
2
(4, 3)


In [7]:
t = tf.constant([1, 2, 3, 4])
tf.shape(t).eval()

array([4], dtype=int32)

In [11]:
t = tf.constant([[1, 2],
                 [3, 4]])
tf.shape(t).eval()

array([2, 2], dtype=int32)

In [12]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4], dtype=int32)

In [8]:
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[1.], [2.]])

print("Matrix 1 shape", matrix1.shape)
print("Matrix 2 shape", matrix2.shape)
tf.matmul(matrix1, matrix2).eval()

Matrix 1 shape (2, 2)
Matrix 2 shape (2, 1)


array([[  5.],
       [ 11.]], dtype=float32)

In [9]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1 + matrix2).eval()

array([[ 5.,  5.]], dtype=float32)

In [10]:
tf.reduce_mean([1., 2.], axis=0).eval()

1.5

In [12]:
x = [[1., 2.],[3., 4]]
tf.reduce_mean(x).eval()

2.5

In [13]:
print(tf.reduce_mean(x, axis=0).eval())
print(tf.reduce_mean(x, axis=1).eval())
print(tf.reduce_mean(x, axis=-1).eval())

[ 2.  3.]
[ 1.5  3.5]
[ 1.5  3.5]


In [16]:
print(tf.reduce_sum(x).eval())
print(tf.reduce_sum(x, axis=0).eval())
print(tf.reduce_sum(x, axis=-1).eval())
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

10.0
[ 4.  6.]
[ 3.  7.]


5.0

In [18]:
x = [[0, 1, 2],
    [2, 1, 0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0])

In [19]:
tf.argmax(x, axis=1).eval()

array([2, 0])

In [20]:
tf.argmax(x, axis=-1).eval()

array([2, 0])

In [21]:
t = np.array([[[0, 1, 2],
              [3, 4, 5]],
             [[6, 7, 8],
             [9, 10 ,11]]])
t.shape

(2, 2, 3)

In [55]:
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

In [27]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [28]:
tf.squeeze([[0], [1], [2]]).eval()

array([0, 1, 2], dtype=int32)

In [31]:
tf.expand_dims([0, 1, 2], 1).eval()

array([[0],
       [1],
       [2]], dtype=int32)

In [33]:
tf.one_hot([[0], [1], [2], [0]], depth=4).eval()

array([[[ 1.,  0.,  0.,  0.]],

       [[ 0.,  1.,  0.,  0.]],

       [[ 0.,  0.,  1.,  0.]],

       [[ 1.,  0.,  0.,  0.]]], dtype=float32)

In [38]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

In [39]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4], dtype=int32)

In [40]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0], dtype=int32)

In [41]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [45]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [48]:
x = [[0, 1, 2],
    [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [49]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [50]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [51]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
